keywords:
  https://x.com: https://fxtwitter.com
  https://twitter.com: https://fxtwitter.com
  https://instagram.com: https://ddinstagram.com
  # https://github.com/wechat-miniprogram/miniprogram-demo/blob/d5cfe3b05d1274a091675f2ed9d475d28e988c1e/miniprogram/packageExtend/components/emoji/emoji.js#L90-L368
  /::): ğŸ˜Š
  /::~: ğŸ˜’
  /::B: ğŸ˜
  /::|: ğŸ˜
  /:8-): ğŸ˜
  /::<: ğŸ˜¢
  /::$: ğŸ˜Š
  /::X: ğŸ¤
  /::Z: ğŸ˜´
  /::"(: ğŸ˜­
  /::-|: ğŸ˜…
  /::@: ğŸ˜ 
  /::P: ğŸ˜œ
  /::D: ğŸ˜
  /::O: ğŸ˜²
  /::(: ğŸ˜
  /::+: ğŸ˜
  /:--b: ğŸ˜°
  /::Q: ğŸ˜±
  /::T: ğŸ¤¢
  /:,@P: ğŸ˜
  /:,@-D: ğŸ˜„
  /::d: ğŸ™„
  /:,@o: ğŸ˜’
  /::g: ğŸ˜‹
  /:|-): ğŸ˜ª
  /::!: ğŸ˜¨
  /::L: ğŸ˜…
  /::>: ğŸ˜„
  /::,@: ğŸ˜
  /:,@f: ğŸ’ª
  /::-S: ğŸ¤¬
  /:?: ğŸ¤”
  /:,@x: ğŸ¤«
  /:,@@: ğŸ˜µ
  /::8: ğŸ¤ª
  /:,@!: ğŸ˜©
  /:!!!: ğŸ’€
  /:xx: ğŸ‘Š
  /:bye: ğŸ‘‹
  /:wipe: ğŸ˜¥
  /:dig: ğŸ™„
  /:handclap: ğŸ‘
  /:&-(: ğŸ¤¦
  /:B-): ğŸ˜
  /:<@: ğŸ˜¤
  /:@>: ğŸ˜¤
  /::-O: ğŸ˜ª
  /:>-|: ğŸ˜’
  /:P-(: ğŸ˜¢
  /::"|: ğŸ˜¥
  /:X-): ğŸ˜
  /::*: ğŸ˜˜
  /:@x: ğŸ˜¨
  /:8*: ğŸ¥º
  /:pd: ğŸ”ª
  /:<W>: ğŸ‰
  /:beer: ğŸº
  /:basketb: ğŸ€
  /:oo: ğŸ“
  /:coffee: â˜•
  /:eat: ğŸš
  /:pig: ğŸ·
  /:rose: ğŸŒ¹
  /:fade: ğŸ¥€
  /:showlove: ğŸ‘„
  /:heart: â¤ï¸
  /:break: ğŸ’”
  /:cake: ğŸ‚
  /:li: âš¡
  /:bome: ğŸ’£
  /:kn: ğŸ”ª
  /:footb: âš½
  /:ladybug: ğŸ
  /:shit: ğŸ’©
  /:moon: ğŸŒ™
  /:sun: â˜€ï¸
  /:gift: ğŸ
  /:hug: ğŸ¤—
  /:strong: ğŸ‘
  /:weak: ğŸ‘
  /:share: ğŸ¤
  /:v: âœŒï¸
  /:@): ğŸ™
  /:jj: ğŸ˜‰
  /:@@: ğŸ‘Š
  /:bad: ğŸ‘
  /:lvu: â¤ï¸
  /:no: ğŸ™…
  /:ok: ğŸ‘Œ
  /:love: ğŸ˜
  /:<L>: ğŸ˜˜
  /:jump: ğŸ’ƒ
  /:shake: ğŸ¥¶
  /:<O>: ğŸ˜ 
  /:circle: ğŸ˜µ
  /:kotow: ğŸ™‡
  /:turn: ğŸ‘€
  /:skip: ğŸ¤¸
  /:oY: ğŸ³ï¸
  /:#-0: ğŸ‰
  /:hiphot: ğŸ•º
  /:kiss: ğŸ˜˜
  /:<&: â˜¯ï¸
  /:&>: â˜¯ï¸
  \ue415: ğŸ˜„
  \ue40c: ğŸ˜·
  \ue412: ğŸ˜‚
  \ue409: ğŸ˜
  \ue40d: ğŸ˜³
  \ue107: ğŸ˜±
  \ue403: ğŸ˜”
  \ue40e: ğŸ˜’
  \ue11b: ğŸ‘»
  \ue41d: ğŸ™
  \ue14c: ğŸ’ª
  \ue312: ğŸ‰
  \ue112: ğŸ
